name: PrisonPicks
main: com.philderbeast.prisonpicks.PrisonPicks
version: 1.2.0
description: PrisonPicks Pickaxes Plugin
author: Philderbeast
depends: ['WorldGuard',
          'AutoPickup'
        ]
commands:
  pick:
    description: Main Command
  fullnotify:
    description: Toggle the Inventory Full Message for Explosive Picks