name: PrisonPicks
main: com.philderbeast.prisonpicks.PrisonPicks
version: {{version}}
description: PrisonPicks Pickaxes Plugin
author: Philderbeast
softdepend: ['WorldGuard',
              'AutoPickup']
commands:
  pick:
    description: Main Command